data_path: '/scratch/shantanu.singh/habitat_data'
train_split_file: 'splits/habitat/habitat_1scene_depth.txt'
val_split_file: 'splits/habitat/habitat_1scene_depth.txt'
load_weights_folder: 'checkpoints/anynet_habitat'
models_to_load: ['disp_module']

log_dir: 'results'
num_epochs: 200
save_frequency: 10
scheduler_step_size: 15
learning_rate: 1e-4
train_workers: 10
val_workers: 5
batch_size: 12
mode: dense

no_ssim: False
avg_bev_reprojection: False
bev_ce_weights: [1.0, 2.0, 8.0] 
loss_weights:
  disparity_loss: 1.0

PIPELINE:
  train: ['DISPARITY'] 
  run: ['DISPARITY'] 

DISPARITY:
  module: 'AnyNet'
  init_channels: 1
  maxdisplist: [12, 3, 3]
  spn_init_channels: 8
  nblocks: 2
  layers_3d: 4
  channels_3d: 4
  growth_rate: [4, 1, 1]
  with_spn: True
  freeze_weights: True
  start_epoch_for_spn: 0
  loss_weights: [0.25, 0.5, 1., 1.]
  max_disparity: 192
  freeze_weights: False

RGBD_ENCODER:
  module: 'concatenate'
  normalize_depth: True
  init_channels: 1
  nblock: 2

BEV_DECODER:
  module: 'monolayout_decoder'
  n_channels: 4
  n_classes: 3

DEBUG:
  extract_depth: 'get_gt_disparity_depth'
  extract_poses: 'get_gt_poses'
  generate_reprojection_pred: 'generate_dense_pred'
  compute_reprojection_losses: 'compute_dense_reprojection_losses'
