data_path: '/scratch/shantanu.singh/HabitatGibson/data'
train_split_file: 'splits/gibson/gibson_train_depth.txt'
val_split_file: 'splits/gibson/gibson_val_depth.txt'
load_weights_folder: 'checkpoints/gt_gibson'
models_to_load: ['disp_module']

log_dir: 'results'
num_epochs: 30
scheduler_step_size: 18
learning_rate: 1e-4
train_workers: 8
val_workers: 2
batch_size: 12
save_frequency: 1
frame_ids: [0]
mode: debug

no_ssim: False
avg_bev_reprojection: False
bev_ce_weights: [1.0, 2.0, 2.0] 
bev_loss_lambda: 0.0
loss_weights:
  bev_loss: 1.0
  gan_loss: 0.01

PIPELINE:
  train: ['BEV', 'DISCR'] 
  run: ['DISPARITY', 'RGBD', 'BEV', 'DISCR'] 

DISPARITY:
  module: 'AnyNet'
  init_channels: 1
  maxdisplist: [12, 3, 3]
  spn_init_channels: 8
  nblocks: 2
  layers_3d: 4
  channels_3d: 4
  growth_rate: [4, 1, 1]
  with_spn: True
  start_epoch_for_spn: 0
  loss_weights: [0.25, 0.5, 1., 1.]
  max_disparity: 192
  freeze_weights: True

RGBD_ENCODER:
  module: 'concatenate'
  normalize_depth: True
  init_channels: 1
  nblock: 2

BEV_DECODER:
  module: 'resnet_layout'
  n_channels: 4
  encoder_lr: 1e-5

DISCRIMINATOR:
  lr: 1e-4
  scheduler_step_size: 100
  discr_train_epoch: 10
  freeze_weights: False

DEBUG:
  extract_depth: 'get_gt_disparity_depth'
  extract_poses: 'get_gt_poses'
  generate_reprojection_pred: 'generate_dense_pred'
  compute_reprojection_losses: 'compute_dense_reprojection_losses'
